---
backupd:
  opensearch:
    backups:
      "465": { client_id: "07c9725629384b6b", enabled: true, region: "gva" }
      "456": { client_id: "4553673c6164c419", enabled: true, region: "gva" }
      "433": { client_id: "4fe2ed584743bf9e", enabled: true, region: "gva" }
